import 'package:aigolive/live-steaming/models/LiveProductModel.dart';
import 'package:flutter/material.dart';

class LiveProductListProvider with ChangeNotifier {
  List<LiveProductModel> _liveProductList = [
    LiveProductModel(
        1,
        'Mixture Grinder',
        'https://www.glenindia.com/400/uploads/product/img/org/58450.jpg',
        3999,
        5160,
        19,
        ['red', 'green'],
        ['s', 'm', 'l']),
    LiveProductModel(
        6,
        'Boy\'s T-shirt',
        'https://images-na.ssl-images-amazon.com/images/I/91SZ3aDkLEL._UX679_.jpg',
        550,
        1000,
        40,
        ['red', 'green'],
        ['s', 'm', 'l']),
    LiveProductModel(
        7,
        'girl\'s T-shirt',
        'https://images-na.ssl-images-amazon.com/images/I/51H46rfOuLL._UL1000_.jpg',
        950,
        1500,
        2,
        ['red', 'green'],
        ['s', 'm', 'l']),
    LiveProductModel(
        9,
        'Toaster 3029',
        'https://www.glenindia.com/400/uploads/product/img/org/GL3019dejRXk.png',
        1339.3,
        1995,
        1, [], []),
    LiveProductModel(
        10,
        'Hand mixture',
        'https://www.glenindia.com/400/uploads/product/img/org/GL-4046-with-prop2drPa7D.jpg',
        196.39,
        2695,
        3,
        ['red', 'green'],
        []),
    LiveProductModel(
        11,
        'Electric Tandoor 5028',
        'https://www.glenindia.com/400/uploads/product/img/org/glen-electric-tandoor-501425640.jpg?1606198823',
        4199,
        5228,
        5,
        ['red', 'green'],
        ['s', 'm', 'l']),
    LiveProductModel(
        12,
        'Bluetooth Adapter',
        'https://images-na.ssl-images-amazon.com/images/I/51k2mS2m4kL._SL1000_.jpg',
        459,
        699,
        30,
        ['red', 'green'],
        ['s', 'm', 'l']),
    LiveProductModel(
        14,
        'Ear Wired Earphones',
        'https://images-na.ssl-images-amazon.com/images/I/61JtJL6Q9oL._SL1500_.jpg',
        99,
        378,
        21,
        ['red'],
        []),
    LiveProductModel(
        15,
        'Wireless Bluetooth 5.0 Headphones',
        'https://images-na.ssl-images-amazon.com/images/I/61HSxuSHiKL._SL1100_.jpg',
        950,
        1500,
        7,
        ['red', 'green'],
        []),
    LiveProductModel(
        16,
        'pTrom Bluetooth Headphones',
        'https://images-na.ssl-images-amazon.com/images/I/51YMl%2BOstqL._SL1100_.jpg',
        950,
        1500,
        9,
        ['red', 'green'],
        []),
  ];
}
